# Generated by Django 2.1.7 on 2019-03-13 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_auto_20190312_2016'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='group_id',
            field=models.IntegerField(default=-1),
        ),
    ]
