# Generated by Django 2.1.7 on 2019-03-14 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0005_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('Planned', 'Planned'), ('Inprogress', 'Inprogress'), ('Done', 'Done')], max_length=100),
        ),
    ]
